version: '3.2'

services:

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: spmb-frontend:latest
    ports:
      - 20080:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: spmb-backend:latest
    ports:
      - 21080:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app

  mariadb:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=spmb
      - MYSQL_USER=sdi
      - MYSQL_PASSWORD=password
    volumes:
      - ./:/docker-entrypoint-initdb.d